---
- name: Install build
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - zlib1g
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip
    - libc6
    - libpcrecpp0
    - libssl0.9.8
    - libssl-dev
    - lsb-base

- name: download nginx
  get_url: dest=/usr/local/src/nginx_{{ nginx_version }}.tar.gz
           url=http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
  register: result
  tags: onece
- debug: var=result

- name: unarchive nginx
  command: tar xvfz nginx_{{ nginx_version }}.tar.gz chdir=/usr/local/src/
  tags: onece
  when: result.msg != 'file already exists'

#- name: download ngx_pagespeed
#  get_url: dest=/usr/local/src/nginx_{{ nginx_version }}.tar.gz
#           url=https://github.com/pagespeed/ngx_pagespeed/archive/release-{{ NPS_VERSION }}-beta.zip
#  tags: onece

#  yum: name={{item}} state=installed
#  with_items:
#    - pcre-devel.x86_64
#    - zlib-devel.x86_64
#    - openssl-devel.x86_64

- name: nginx configure
  command: >
    chdir=/usr/local/src/nginx-{{ nginx_version }}
    ./configure
    --prefix=/etc/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --error-log-path=/var/log/nginx/error.log
    --http-log-path=/var/log/nginx/access.log
    --pid-path=/var/run/nginx.pid
    --lock-path=/var/run/nginx.lock
    --http-client-body-temp-path=/var/cache/nginx/client_temp
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp
    --user=nginx
    --group=nginx
    --with-http_ssl_module
    --with-http_realip_module
    --with-http_addition_module
    --with-http_sub_module
    --with-http_dav_module
    --with-http_flv_module
    --with-http_mp4_module
    --with-http_gunzip_module
    --with-http_gzip_static_module
    --with-http_random_index_module
    --with-http_secure_link_module
    --with-http_stub_status_module
    --with-mail
    --with-mail_ssl_module
    --with-file-aio
    --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'
  when: result.msg != 'file already exists'

- command: make chdir=/usr/local/src/nginx-{{ nginx_version }}
  when: result.msg != 'file already exists'

- command: make install chdir=/usr/local/src/nginx-{{ nginx_version }}
  when: result.msg != 'file already exists'

- name: set nginx init conf
  template: >
    src=nginx_init_deb.j2
    dest=/etc/init.d/nginx
    mode=0755

- name: set nginx.conf
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    mode=0644
